stages:
  - test
  - build
  - deploy

test-job:
  stage: test
  script:
    - echo "Running tests... This will take about 60 seconds."
    - sleep 60
    - echo "Tests complete."

build-job:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

deploy-job:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
